<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/** @var yii\web\View $this */
/** @var backend\models\Grupo $model */

$this->title = $model->Id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Grupos'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="grupo-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'Id' => $model->Id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'Id' => $model->Id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'Id',
            'primeiroReporte',
            'actualizacaoID',
            'respondente',
            'entidade',
            'provinciaID',
            'municipioID',
            'comunaID',
            'localidadeID',
            'latitude',
            'longitude',
            'apoioAgricola',
            'nomeGrupo',
            'grupoExistia',
            'metodologiaAgricola',
            'outraMetodologiaAgricola',
            'segueMetodologiaECA',
            'anoInicioApoio',
            'primeiroAnoAgriColheita',
            'ultimoAnoAgriColheita',
            'estagioFaseEncontra',
            'validadaIDA',
            'grupoEntregueEntPubl',
            'dataGrupoEntregue',
            'anexoAutoEntrega',
            'primeiraFinalidadeID',
            'segundaFinalidadeID',
            'terceiraFinalidadeID3',
            'beneficiariosHomem',
            'beneficiariosMulher',
            'listaMembros',
            'representaQtsAF',
            'bovinos',
            'caprinos',
            'ovinos',
            'temComissaoGestao',
            'temReguInterno',
            'temFacilitador',
            'temParcelasAprendizagem',
            'temCerco',
            'temPlacaIdentificacao',
            'temCadernoRegisto',
            'contribuicaoFundoManeio',
            'frequenciaContribuicoes',
            'membrosContribuemRegular',
            'fundoManeioSaldoPositivo',
            'temPlanoActividade',
            'frequenciaSessoes',
            'localReunioes',
            'implementaASAE',
            'produzBioInsecticida',
            'usaBioFertilizante',
            'integraSistemaAgrosilvopastoril',
            'numEvenTrocExperCamponeses',
            'metodologiaJangosPastoris',
            'assistTecnApoioProducao',
            'placaVisibilidade',
            'autoridadeTradEnvolvida',
            'administracaoEnvolvida',
            'isvEnvolvida',
            'idfEnvolvida',
            'idaEdaEnvolvida',
            'iiaEnvolvida',
            'iivEnvolvida',
            'outroEnvolvida',
            'primeiraPraticaInovadora',
            'segundaPraticaInovadora',
            'terceiraPraticaInovadora',
            'replicaPraticaInovadora',
            'nLavrasPartiReplicaPraticaInovadora',
            'principalConstrangimento',
            'temas:ntext',
            'tema1Ciclo',
            'tema2Ciclo',
            'tema3Ciclo',
            'outroTema:ntext',
            'nSessoeTeoPrat',
            'nSessoeTeoPratTrimes',
            'diaSessaoEca',
            'percentParticipacao',
            'areaTotalCampoAgro',
            'areaCultivadaCampoAgro',
            'areaInsPlantInovadorasCampoAgro',
            'pontoAguaDispoIrri',
            'previstConstrSistIrrig',
            'sistemaIrriUtilizad',
            'areaIrrigada',
            'classificacacaoCampo',
            'houveExcedente',
            'culturasHouveExcedente',
            'qtdExcedente',
            'trimestreExcedente',
            'destinoExcedente',
            'facilitaLigacoesEntreProdutores',
            'realizaEventosSobreProdutos',
            'apoioDistrProdCamponeses',
            'nRedes',
            'dataApoios',
            'tipoEvento',
            'descricaoRede:ntext',
            'coberturaGeograficaRede',
            'comerciantesEnvolvidos',
            'finalidadeRede',
            'frequenciaRede',
            'resultadoInicRede',
            'desafios',
            'licoesAprendidas',
            'temBancoSementes',
            'fazMultiSementes',
            'culturasDispoBancSementes:ntext',
            'qtdSementesEntrBancoKG',
            'trimSementesBanco',
            'totalSementesEntrCamponeses',
            'trimestreSementesEntrCamponeses',
            'totalSementesReembPelosCamponeses',
            'trimestreSementesReembPelosCamponeses',
            'qtdSementesDisponiveisBanco',
            'trimestreSementesDisponiveisBanco',
            'estadoBancoSementes',
            'temRegistoBancSementes',
            'camponesesRecebemSementesBanc',
            'camponesesReebolsaSementesBanc',
            'resultadIniciBancoSem',
            'desafiosBancoSem:ntext',
            'licoesAprendiBancSem:ntext',
            'classifCooper',
            'membrCampoAgrFormal',
            'homemCoop',
            'mulherCoop',
            'coopExistia',
            'coopLegalizada',
            'coopLegalFresan',
            'tipoApoioDadoProjec',
            'realizaFormacao',
            'temaSessoesFormacao:ntext',
            'nSessoesFormacoes',
            'trimesSessoesFormacoes',
            'orgaosSociaisDefinidos',
            'nReunioesOrgSoc',
            'nReunioesOrgSocTrimestre',
            'membrosFazemContrReg',
            'coopTemFundoManeioPositivo',
            'propositoApoiarTransformacao',
            'realizaTransforDescriProduto:ntext',
            'propositoApoiarArmazen',
            'propositoApoiarFactorProd',
            'propositoApoiarComercializacao',
            'propositoApoiarMembroCaixaCom',
            'desafiosCooperativas:ntext',
            'licoesAprendidasCooperativas:ntext',
            'tecnologiaProjectoPioto',
            'nCamponesesHomens',
            'nCamponesesMulheres',
            'kitClassificacao',
            'kitDistribuidoDescric:ntext',
            'nKitEntregue',
            'pontoSituacaoProjecto',
            'comercializacao',
            'qtdProdComercializadoKG',
            'resultadoInicPiloto',
            'desafiosPiloto:ntext',
            'licoesAprendidasPiloto:ntext',
            'realizadaSinsibilizacoesEAN',
            'realizadasSensibilizacoesCulinarias',
            'realizadoRastreios',
            'desafiosAprendidasONG',
            'licoesAprendidasONG',
            'dataVisitaUIC',
            'tecnicoResponsavelUIC',
            'constatacoesFeitasUIC',
            'recomendacoesFeitasUIC:ntext',
            'medidasMitigacaoONG',
            'medidasMitigacaoEstado',
            'userID',
        ],
    ]) ?>

</div>
