<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '\'{class}\' must extend from \'yii\\rbac\\Rule\' or its child class' => '\'{class}\' must extend from \'yii\\rbac\\Rule\' or its child class',
    'Action' => 'Action',
    'Are you sure to delete this item?' => 'Você tem certeza que pretende eliminar este Item?',
    'Assign' => 'Assign',
    'Assignment : {0}' => 'Atribuição : {0}',
    'Assignments' => 'Atribuiçoes',
    'Class Name' => 'Class Name',
    'Create' => 'Criar',
    'Create Rule' => 'Criar Regra',
    'Create Role' => 'Create Role',
    'Data' => 'Data',
    'Delete' => 'Eliminar',
    'Description' => 'Descrição',
    'Invalid rule "{value}"' => 'Regra Invãlida "{value}"',
    'Item has been removed.' => 'Item has been removed.',
    'Item has been saved.' => 'Item Salvo com sucesso.',
    'Name' => 'Nome',
    'Permissions' => 'Permissão',
    'Refresh' => 'Actualizar',
    'Remove' => 'Remover',
    'Roles' => 'Função',
    'Role : {0}' => 'Função : {0}',
    'Permission : {0}' => 'Permissão : {0}',
    'Create Permission' => 'Criar Permissão',
    'Routes' => 'Rotas',
    'Rule' => 'Rule',
    'Rule "{value}" does not exists' => 'Regra "{value}" Não Existe',
    'Rule : {0}' => 'Rule : {0}',
    'Rule Name' => 'Rule Name',
    'Rule has been deleted.' => 'Rule has been deleted.',
    'Rule has been saved.' => 'Rule has been saved.',
    'Rules' => 'Rules',
    'Search for assigned' => 'Search for assigned',
    'Search for available' => 'Search for available',
    'The requested page does not exist.' => 'The requested page does not exist.',
    'Type' => 'Type',
    'Unknown class \'{class}\'' => 'Unknown class \'{class}\'',
    'Update' => 'Update',
    'Update Rule : {0}' => 'Update Rule : {0}',
    'Update Role : {0}' => 'Update Role : {0}',
    'Update Permission : {0}' => 'Actualizar Permissão : {0}',
    'Select Rule' => 'Select Rule',
];
